
== Créer un équipement Google Agenda

Côté Jeedom il faut créer un équipement Google Agenda et ainsi obtenir l'URL de redirection

== Créer un compte développeur chez Google 

Il faut créer un compte développeur chez Google pour avoir accès aux API, allez sur https://console.developers.google.com/apis/credentials[ici] puis faîtes "Créer identifiants" et "ID clinet Oauth", sélectionnez "Application Web" et dans "URL de redirection autorisée" mettez celle donnée sur la page de configuration de l'équipement Jeedom.

Récupérez la clef client et le secret client (il faudra les mettre côté Jeedom dans l'équipement)

Il faut ensuite ajouter l'API Google Calendar en allant sur https://console.developers.google.com/apis/dashboard[ici], puis en faisant "Activer l'api" et recherchez "Google Calendar API" puis ajoutez-la.

== Liez le compte Google à Jeedom

Copiez la clef client et le secrey client côté Jeedom puis cliquez sur le bouton Lier, validez

== Commande

Le plugin ne comporte qu'une commande qui vous donne le titre de l'événement en cours

== Interaction

Jeedom peut interpréter le titre d'un événement comme une interaction et donc déclencher une action. Pour cela il faut activer les interactions sur la page de configuration de l'équipement.

Vous pouvez aussi indiquer une commande de retour par laquelle Jeedom va répondre suite à l'exécution de l'interaction.
